#!/usr/bin/bash
#
# fsl-maker - A help script to compose the Security Lab Live media.
# Copyright (c) 2010-2014 Fabian Affolter <fab@fedoraproject.org>
#
# All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#
KICKSTART=fedora-livecd-security.ks
DIRECTORY=spin-kickstarts
CACHE=/var/cache/live
LABEL=SecurityLab
TITLE=SecurityLab-`date -I`
#RELEASEVER=20
RELEASEVER=rawhide
ROOT_UID=0   

# Check if livecd-creator is available
if [ ! -e /usr/bin/livecd-creator ]
    then
        echo "livecd-creator is not installed. Installation starts now ..."
        sudo yum -y install livecd-tools
fi

# Check if the spin-kickstarts directory is present
if [ -d ../$DIRECTORY ]
    then
        echo "Updating the spin-kickstarts git repository."
        ( cd ../$DIRECTORY && git pull origin master)
    else
        echo "Getting the spin-kickstarts git repository." 
        ( cd .. && git clone ssh://git.fedorahosted.org/git/spin-kickstarts.git )
fi

# Set SELinux to permissive mode
sudo setenforce 0

# Create the live media. This needs time...
sudo livecd-creator \
    --verbose \
    --config=../$DIRECTORY/$KICKSTART \
    --fslabel=$LABEL \
    --title=$TITLE \
    --releasever=$RELEASEVER
#    --cache=$CACHE \

echo ""
echo "If this script finished with no error, then the image is ready."
