#!/bin/bash
#
# fsl-virt-inst - Creator for a libvirt-based virtual machine for the Fedora
# Security Lab Test bench.
#
# Copyright (c) 2012-2014 Fabian Affolter <fab@fedoraproject.org>
#
# All rights reserved.
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#

cat <<END_ENTRY >> fsl-testbench.ks
# Minimal Kickstart file for the Fedora Security Lab test bench
# Installation, not an upgrade
install

# No graphical things needed
skipx
text

# Language
lang en_US.UTF-8

# Keyboard setup
keyboard sg-latin1
#keyboard us

# Networking
network --onboot yes --device eth0 --bootproto dhcp --ipv6 auto --hostname test-bench

# Authentication
auth --enableshadow --passalgo=sha512
#rootpw {{ server_root_password }}
rootpw testbench

# Services, SELinux and firewall
firewall --enabled --ssh
services --enabled network,sshd
selinux --enforcing
#firstboot --disable
logging --level=info

# Time zone
timezone Europe/Zurich

# Disk setup
zerombr
bootloader --location=mbr --append="rd_NO_PLYMOUTH"
ignoredisk --only-use=vda
clearpart --none --initlabel --drives=vda
autopart

poweroff

%packages
@core
chrony
#dnf
bash-completion
tar
unzip
git
%end
END_ENTRY

sudo virt-install \
    --name FSL-Test-bench \
    --os-variant fedora20 \
    --ram 1024 \
    --disk /var/lib/libvirt/images/fsl-tb-f20.img,size=8 \
    --location http://mirror.switch.ch/ftp/mirror/fedora/linux/releases/20/Fedora/x86_64/os/ \
    --initrd-inject fsl-testbench.ks \
    --extra-args "ks=file:fsl-testbench.ks" \
    --noautoconsole \
    --vnc \
    --network=network:default \
    --mac=52:52:00:00:00:01

rm fsl-testbench.ks
